# configuration file for variables used in the program

imageSizeY: 640
imageSizeX: 640
averageSizeOfFish: 70

dataDirectory: 'data'

shouldAddPatchyNoise: True

# Small values for debugging purposes
amountOfData: 5
fractionForTraining: 1

